In [1]:


def image_load(path):
    import os
    import re # 데이터 정제 패키지
    import cv2
    import numpy as np

    test_image = "c:\\image"
    file_list = os.listdir(path)
    #return file_list
    file_name = []
    for i in file_list:
        a = int( re.sub('[^0-9]','',i) ) # 숫자가 아닌 것은 null 처리
        file_name.append(a)
    file_name.sort()
    for j in range(len(file_list)):
        file_name[j] = path+'\\'+str(j+1)+'.png' 
    
    image = []
    for k in file_name:
        img = cv2.imread(k) # 파일을 읽어서 숫자 행렬로 변환
        image.append(img) 
        
    return np.array(image) # 숫자 행렬 리스트를 numpy array로 감싼다.

print(image_load(test_image))



[array([[[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [182, 182, 182],
        [187, 187, 187],
        [191, 191, 191]],

       [[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [173, 173, 173],
        [179, 179, 179],
        [186, 186, 186]],

       [[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [170, 170, 170],
        [173, 173, 173],
        [176, 176, 176]],

       ...,

       [[108, 108, 108],
        [108, 108, 108],
        [109, 109, 109],
        ...,
        [ 75,  75,  75],
        [ 75,  75,  75],
        [ 78,  78,  78]],

       [[ 85,  85,  85],
        [ 85,  85,  85],
        [ 86,  86,  86],
        ...,
        [ 77,  77,  77],
        [ 77,  77,  77],
        [ 80,  80,  80]],

       [[ 86,  86,  86],
        [ 86,  86,  86],
        [ 87,  87,  87],
        ...,
        [ 87,  87,  87],
        [ 87,  87,  87],
        [ 90,  90,  90]

In [1]:
from my_loc import lung_loader as l
#test_image = "c:\\image"

l.image_load(l.test_image) 

[array([[[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [182, 182, 182],
        [187, 187, 187],
        [191, 191, 191]],

       [[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [173, 173, 173],
        [179, 179, 179],
        [186, 186, 186]],

       [[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [170, 170, 170],
        [173, 173, 173],
        [176, 176, 176]],

       ...,

       [[108, 108, 108],
        [108, 108, 108],
        [109, 109, 109],
        ...,
        [ 75,  75,  75],
        [ 75,  75,  75],
        [ 78,  78,  78]],

       [[ 85,  85,  85],
        [ 85,  85,  85],
        [ 86,  86,  86],
        ...,
        [ 77,  77,  77],
        [ 77,  77,  77],
        [ 80,  80,  80]],

       [[ 86,  86,  86],
        [ 86,  86,  86],
        [ 87,  87,  87],
        ...,
        [ 87,  87,  87],
        [ 87,  87,  87],
        [ 90,  90,  90]

array([array([[[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [182, 182, 182],
        [187, 187, 187],
        [191, 191, 191]],

       [[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [173, 173, 173],
        [179, 179, 179],
        [186, 186, 186]],

       [[ 16,  16,  16],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [170, 170, 170],
        [173, 173, 173],
        [176, 176, 176]],

       ...,

       [[108, 108, 108],
        [108, 108, 108],
        [109, 109, 109],
        ...,
        [ 75,  75,  75],
        [ 75,  75,  75],
        [ 78,  78,  78]],

       [[ 85,  85,  85],
        [ 85,  85,  85],
        [ 86,  86,  86],
        ...,
        [ 77,  77,  77],
        [ 77,  77,  77],
        [ 80,  80,  80]],

       [[ 86,  86,  86],
        [ 86,  86,  86],
        [ 87,  87,  87],
        ...,
        [ 87,  87,  87],
        [ 87,  87,  87],
        [ 90,  90

In [10]:
import cv2 # 이미지를 숫자로 바꾸는 모듈
import os # os에서 파일 위치 차즌 모듈
import numpy as np

path = "c:\\image" 

file_list = os.listdir(path) # 파일명 가져오기

for k in file_list: # 파일명 리스트를 하나씩 가져온다.
    img = cv2.imread(path + '\\' + k) # 사진을 숫자 행렬로 변환
    width, height = img.shape[:2] # 행렬 shape를 가져온다.
    resize_img = cv2.resize(img, (32 , 32), interpolation=cv2.INTER_CUBIC) 
    #32x32로 리사이즈
    cv2.imwrite('c:\\train_resize\\' + k, resize_img)

In [16]:

import os
import re # 데이터 정제 패키지
import cv2 # 이미지를 숫자로 변환하는 모듈
import numpy as np # 신경망에서 행렬연산을 쉽게 하기 위해 필요

#test_image = "c:\\image"
image_path = "C:\\data\\test\\test"

def image_load(path):
    file_list = os.listdir(path)
    #return file_list
    file_name = []
    for i in file_list:
        a = int( re.sub('[^0-9]','',i) ) # 숫자가 아닌 것은 null 처리
        file_name.append(a)
    file_name.sort()
    for j in range(len(file_list)):
        file_name[j] = path+'\\'+str(j+1)+'.jpg' 
        #file_name[j] = path+'%s\\'+str(%d+1)+'.png'         
    
    image = []
    for k in file_name:
        img = cv2.imread(k) # 파일을 읽어서 숫자 행렬로 변환
        image.append(img) 
        
    return np.array(image) # 숫자 행렬 리스트를 numpy array로 감싼다.

print(image_load(image_path))


KeyboardInterrupt: 

In [17]:

import os
import re # 데이터 정제 패키지
import cv2 # 이미지를 숫자로 변환하는 모듈
import numpy as np # 신경망에서 행렬연산을 쉽게 하기 위해 필요

#test_image = "c:\\image"
image_path = "C:\\catdog"

def image_load(path):
    file_list = os.listdir(path)
    #return file_list
    file_name = []
    for i in file_list:
        a = int( re.sub('[^0-9]','',i) ) # 숫자가 아닌 것은 null 처리
        file_name.append(a)
    file_name.sort()
    for j in range(len(file_list)):
        file_name[j] = path+'\\'+str(j+1)+'.jpg' 
        #file_name[j] = path+'%s\\'+str(%d+1)+'.png'         
    
    image = []
    for k in file_name:
        img = cv2.imread(k) # 파일을 읽어서 숫자 행렬로 변환
        image.append(img) 
        
    return np.array(image) # 숫자 행렬 리스트를 numpy array로 감싼다.

print(image_load(image_path))


[array([[[ 94,  64,  37],
        [ 92,  62,  35],
        [ 95,  60,  34],
        ...,
        [201, 107,  71],
        [175,  86,  49],
        [173,  85,  48]],

       [[ 98,  68,  41],
        [ 96,  66,  39],
        [ 98,  63,  37],
        ...,
        [200, 106,  71],
        [174,  85,  48],
        [172,  84,  47]],

       [[102,  72,  45],
        [100,  70,  43],
        [101,  66,  40],
        ...,
        [199, 105,  70],
        [173,  83,  48],
        [171,  83,  47]],

       ...,

       [[172, 169, 165],
        [175, 170, 167],
        [179, 174, 171],
        ...,
        [ 70,  89,  96],
        [ 56,  78,  84],
        [ 54,  77,  85]],

       [[173, 172, 168],
        [174, 173, 169],
        [180, 175, 172],
        ...,
        [ 90, 107, 116],
        [ 74,  97, 105],
        [ 75,  97, 108]],

       [[178, 177, 173],
        [177, 176, 172],
        [180, 175, 172],
        ...,
        [ 99, 116, 125],
        [ 84, 107, 115],
        [ 85, 107, 118]

In [3]:
from my_loc import catdog_loader as cl

test_image = "c:\\catdog"

print( cl.image_load(test_image) )

[array([[[ 94,  64,  37],
        [ 92,  62,  35],
        [ 95,  60,  34],
        ...,
        [201, 107,  71],
        [175,  86,  49],
        [173,  85,  48]],

       [[ 98,  68,  41],
        [ 96,  66,  39],
        [ 98,  63,  37],
        ...,
        [200, 106,  71],
        [174,  85,  48],
        [172,  84,  47]],

       [[102,  72,  45],
        [100,  70,  43],
        [101,  66,  40],
        ...,
        [199, 105,  70],
        [173,  83,  48],
        [171,  83,  47]],

       ...,

       [[172, 169, 165],
        [175, 170, 167],
        [179, 174, 171],
        ...,
        [ 70,  89,  96],
        [ 56,  78,  84],
        [ 54,  77,  85]],

       [[173, 172, 168],
        [174, 173, 169],
        [180, 175, 172],
        ...,
        [ 90, 107, 116],
        [ 74,  97, 105],
        [ 75,  97, 108]],

       [[178, 177, 173],
        [177, 176, 172],
        [180, 175, 172],
        ...,
        [ 99, 116, 125],
        [ 84, 107, 115],
        [ 85, 107, 118]

In [5]:
a= [[1,2],[3,4]]
b= [[10,20],[30,40]]
c=[[0,0],[0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j] = a[i][j]+b[i][j]
        
print(c)

[[11, 22], [33, 44]]


In [13]:
import numpy as np
a= [[1,2],[3,4]]
b= [[10,20],[30,40]]
an = np.array(a)
bn = np.array(b)

print(an+bn)

[[11 22]
 [33 44]]


In [11]:
[[0]*3]*2

[[0, 0, 0], [0, 0, 0]]

In [16]:
import numpy as np

t = np.array([[1,6],[7,3]])
t +5

array([[ 6, 11],
       [12,  8]])

In [17]:
import numpy as np

an = np.array([[1,2],[3,4]])
bn = np.array([10,20])

print(an*bn)

[[10 40]
 [30 80]]


In [25]:
import numpy as np

an = np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
bn = np.array([[2,0,1],[0,1,2],[1,0,2]])
rn = np.array([[0]*(an.shape[0]-bn.shape[0]+1)]*(an.shape[1]-bn.shape[1]+1))
print(an)
print(bn)
print(rn)
for i in range(an.shape[0]-bn.shape[0]):
    for i in range(an.shape[1]-bn.shape[1]):
        

[[1 2 3 0]
 [0 1 2 3]
 [3 0 1 2]
 [2 3 0 1]]
[[2 0 1]
 [0 1 2]
 [1 0 2]]
[[0 0]
 [0 0]]


In [32]:
import numpy as np
x = np.array([[1,2,3],[0,1,2],[3,0,1]])
filter = np.array([[2,0,1],[0,1,2],[1,0,2]])

# print(x.shape)
# print(filter.shape)

# print(np.sum(x*filter))
print(x[:2][::][0])

[1 2 3]


In [42]:
import numpy as np

an = np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])

an

an[0:3,0:3]

array([[1, 2, 3],
       [0, 1, 2],
       [3, 0, 1]])

In [51]:
import numpy as np

an = np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])
bn = np.array([[2,0,1],[0,1,2],[1,0,2]])
rn = np.array([[0]*(an.shape[0]-bn.shape[0]+1)]*(an.shape[1]-bn.shape[1]+1))
print(an)
print(bn)
print(rn)
for i in range(an.shape[0]-bn.shape[0]):
    for j in range(an.shape[1]-bn.shape[1]):
        print(a[i:i+bn.shape[0],j:j+bn.shape[1]])

[[1 2 3 0]
 [0 1 2 3]
 [3 0 1 2]
 [2 3 0 1]]
[[2 0 1]
 [0 1 2]
 [1 0 2]]
[[0 0]
 [0 0]]
<class 'int'>


In [45]:
import numpy as np

an = np.array([[1,2,3,0],[0,1,2,3],[3,0,1,2],[2,3,0,1]])

an

an[1:,:3]

array([[0, 1, 2],
       [3, 0, 1],
       [2, 3, 0]])

In [48]:
result = [2,3,4,5]

import numpy as np
np.array(result).reshape(1,4)

array([[2, 3, 4, 5]])

In [64]:
import numpy as np

an = np.array([[1,2,3,0,1],[0,1,2,3,1],[3,0,1,2,1],[2,3,0,1,1]])
bn = np.array([[2,0],[0,1]])
rn = np.array([[0]*(an.shape[1]-bn.shape[1]+1)]*(an.shape[0]-bn.shape[0]+1))
print(an)
print(bn)
print(rn)
for i in range(an.shape[0]-bn.shape[0]+1):
    for j in range(an.shape[1]-bn.shape[1]+1):
        rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
print(rn)

[[1 2 3 0 1]
 [0 1 2 3 1]
 [3 0 1 2 1]
 [2 3 0 1 1]]
[[2 0]
 [0 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[3 6 9 1]
 [0 3 6 7]
 [9 0 3 5]]


In [120]:
import numpy as np

an = np.array([[1,2,3],[0,1,2],[3,0,1]])
bn = np.array([[2,0,1],[0,1,2],[1,0,2]])
rn = np.array([[0]*(an.shape[0]-bn.shape[0]+1)]*(an.shape[1]-bn.shape[1]+1))
print(an)
print(bn)
#print(rn)
for i in range(an.shape[0]-bn.shape[0]+1):
    for j in range(an.shape[1]-bn.shape[1]+1):
        rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
print(rn)

[[1 2 3]
 [0 1 2]
 [3 0 1]]
[[2 0 1]
 [0 1 2]
 [1 0 2]]
[[15]]


In [122]:
an = np.array([[1,2,3],[0,1,2],[3,0,1]])
print(len(an.shape))

2


In [114]:
import numpy as np
import math
s = 2
bias = 1
an = np.array([[[0,0,0,0,0,0,0],[0,2,2,1,1,0,0],[0,0,0,1,0,0,0],[0,0,2,0,0,1,0],[0,1,2,1,1,2,0],[0,1,0,1,0,1,0],[0,0,0,0,0,0,0]],
[[0,0,0,0,0,0,0],[0,2,0,0,0,1,0],[0,0,2,2,0,1,0],[0,0,0,0,0,2,0],[0,0,1,2,0,1,0],[0,2,0,2,2,2,0],[0,0,0,0,0,0,0]],
[[0,0,0,0,0,0,0],[0,1,1,0,1,1,0],[0,0,1,0,1,2,0],[0,0,2,2,0,0,0],[0,0,2,0,0,1,0],[0,1,1,2,1,1,0],[0,0,0,0,0,0,0]]])
bn = np.array([[[1,1,-1],[-1,0,0],[1,1,0]],[[-1,-1,0],[0,-1,1],[0,-1,0]],[[-1,1,1],[-1,1,-1],[0,0,-1]]])
rn = np.array([[0]*math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)]*math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s))
# print(an)
# print(bn)
# print(rn)

for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
    for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
        for k in range(len(bn)):
#             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
#             print(bn[k])
#             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
            rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn)-2],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
#             print(' ',k)
#             print('  ',i)
#             print('   ',j)
#             print(rn)
print(rn+bias)
#print(math.ceil((an.shape[1]-bn.shape[1]+1)/2))

[[[0 0 0 0 0 0 0]
  [0 2 2 1 1 0 0]
  [0 0 0 1 0 0 0]
  [0 0 2 0 0 1 0]
  [0 1 2 1 1 2 0]
  [0 1 0 1 0 1 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 2 0 0 0 1 0]
  [0 0 2 2 0 1 0]
  [0 0 0 0 0 2 0]
  [0 0 1 2 0 1 0]
  [0 2 0 2 2 2 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 1 1 0 1 1 0]
  [0 0 1 0 1 2 0]
  [0 0 2 2 0 0 0]
  [0 0 2 0 0 1 0]
  [0 1 1 2 1 1 0]
  [0 0 0 0 0 0 0]]]
[[[ 1  1 -1]
  [-1  0  0]
  [ 1  1  0]]

 [[-1 -1  0]
  [ 0 -1  1]
  [ 0 -1  0]]

 [[-1  1  1]
  [-1  1 -1]
  [ 0  0 -1]]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[-2 -5 -2]
 [-1 -3  1]
 [ 0 -2  2]]


In [97]:
bn = np.array([[[1,1,-1],[-1,0,0],[1,1,0]],[[-1,-1,0],[0,-1,1],[0,-1,0]],[[-1,1,1],[-1,1,-1],[0,0,-1]]])

print(bn[1])

[[-1 -1  0]
 [ 0 -1  1]
 [ 0 -1  0]]


In [111]:
an = np.array([[[0,0,0,0,0,0,0],[0,2,2,1,1,0,0],[0,0,0,1,0,0,0],[0,0,2,0,0,1,0],[0,1,2,1,1,2,0],[0,1,0,1,0,1,0],[0,0,0,0,0,0,0]],
[[0,0,0,0,0,0,0],[0,2,0,0,0,1,0],[0,0,2,2,0,1,0],[0,0,0,0,0,2,0],[0,0,1,2,0,1,0],[0,2,0,2,2,2,0],[0,0,0,0,0,0,0]],
[[0,0,0,0,0,0,0],[0,1,1,0,1,1,0],[0,0,1,0,1,2,0],[0,0,2,2,0,0,0],[0,0,2,0,0,1,0],[0,1,1,2,1,1,0],[0,0,0,0,0,0,0]]])

print(an.shape)

(3, 7, 7)


In [115]:

def xx(m_a,filt,s,bias):
    import numpy as np
    import math
    #s = 2
    #bias = 1
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)]*math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s))
    # print(an)
    # print(bn)
    # print(rn)

    for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
        for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
            for k in range(len(bn)):
    #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
    #             print(bn[k])
    #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn)-2],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
    #             print(' ',k)
    #             print('  ',i)
    #             print('   ',j)
    #             print(rn)
    print(rn+bias)
#print(math.ceil((an.shape[1]-bn.shape[1]+1)/2))

[[-2 -5 -2]
 [-1 -3  1]
 [ 0 -2  2]]


In [126]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
    #s = 2
    #bias = 1
        
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
    # print(an)
    # print(bn)
    # print(rn)

    for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
        for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
            for k in range(len(bn)):
    #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
    #             print(bn[k])
    #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn)-2],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
    #             print(' ',k)
    #             print('  ',i)
    #             print('   ',j)
    #             print(rn)
    print(rn+bias)
a1 = [[1,2,3],[0,1,2],[3,0,1]]
a2 = [[2,0,1],[0,1,2],[1,0,2]]
s1 = 1
b1 = 0
xx(a1,a2,s1,b1)

IndexError: tuple index out of range

In [123]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
    #s = 2
    #bias = 1
    
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)]*math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s))
    # print(an)
    # print(bn)
    # print(rn)
    if len(an.shape) == 2:
        for i in range(an.shape[0]-bn.shape[0]+1):
            for j in range(an.shape[1]-bn.shape[1]+1):
                rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
        return rn
    else:
        
        for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
            for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
                for k in range(len(bn)):
        #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
        #             print(bn[k])
        #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                    rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn)-2],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
        #             print(' ',k)
        #             print('  ',i)
        #             print('   ',j)
        #             print(rn)
        return rn+bias
a1 = [[1,2,3],[0,1,2],[3,0,1]]
a2 = [[2,0,1],[0,1,2],[1,0,2]]
s1 = 1
b1 = 0
xx(a1,a2,s1,b1)

IndexError: tuple index out of range

In [131]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
    #s = 2
    #bias = 1
        
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
    # print(an)
    # print(bn)
    # print(rn)

    for i in range(math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s)):
        for j in range(math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)):
            for k in range(len(bn)):
    #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
    #             print(bn[k])
    #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn.shape)-2],j*s:j*s+bn.shape[len(bn.shape)-1]]*bn[k])
    #             print(' ',k)
    #             print('  ',i)
    #             print('   ',j)
    #             print(rn)
    print(rn+bias)
a1 = [[1,2,3],[0,1,2],[3,0,1]]
a2 = [[2,0,1],[0,1,2],[1,0,2]]
#s1 = 1
#b1 = 0
xx(a1,a2)

IndexError: too many indices for array

In [137]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
    #s = 2
    #bias = 1
        
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
    # print(an)
    # print(bn)
    # print(rn)
    if len(an.shape) == 2:
        for i in range(an.shape[0]-bn.shape[0]+1):
            for j in range(an.shape[1]-bn.shape[1]+1):
                rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
        return rn+bias
    
    else:
        for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
            for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
                for k in range(len(bn)):
        #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
        #             print(bn[k])
        #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                    rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn)-2],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
        #             print(' ',k)
        #             print('  ',i)
        #             print('   ',j)
        #             print(rn)
        return rn+bias
a1 = [[[0,0,0,0,0,0,0],[0,2,2,1,1,0,0],[0,0,0,1,0,0,0],[0,0,2,0,0,1,0],[0,1,2,1,1,2,0],[0,1,0,1,0,1,0],[0,0,0,0,0,0,0]],
[[0,0,0,0,0,0,0],[0,2,0,0,0,1,0],[0,0,2,2,0,1,0],[0,0,0,0,0,2,0],[0,0,1,2,0,1,0],[0,2,0,2,2,2,0],[0,0,0,0,0,0,0]],
[[0,0,0,0,0,0,0],[0,1,1,0,1,1,0],[0,0,1,0,1,2,0],[0,0,2,2,0,0,0],[0,0,2,0,0,1,0],[0,1,1,2,1,1,0],[0,0,0,0,0,0,0]]]
a2 = [[[1,1,-1],[-1,0,0],[1,1,0]],[[-1,-1,0],[0,-1,1],[0,-1,0]],[[-1,1,1],[-1,1,-1],[0,0,-1]]]
s1 = 2
b1 = 1
print(xx(a1,a2,s1,b1))

[[-2 -5 -2]
 [-1 -3  1]
 [ 0 -2  2]]


In [132]:
import numpy as np
import math
#s = 2
#bias = 1
a1 = [[1,2,3],[0,1,2],[3,0,1]]
a2 = [[2,0,1],[0,1,2],[1,0,2]]

an = np.array(a1)
bn = np.array(a2)
rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
# print(an)
# print(bn)
# print(rn)

for i in range(math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s)):
    for j in range(math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)):
        for k in range(len(bn)):
#             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
#             print(bn[k])
#             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
            rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn.shape)-2],j*s:j*s+bn.shape[len(bn.shape)-1]]*bn[k])
#             print(' ',k)

IndexError: too many indices for array

In [143]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
    #s = 2
    #bias = 1
        
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
    # print(an)
    # print(bn)
    print(rn)
#     if len(an.shape) == 2:
#         for i in range(an.shape[0]-bn.shape[0]+1):
#             for j in range(an.shape[1]-bn.shape[1]+1):
#                 rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
#         return rn+bias
    
    else:
        for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
            for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
                for k in range(len(bn)):
        #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
        #             print(bn[k])
        #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                    rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn.shape)-2],j*s:j*s+bn.shape[len(bn.shape)-1]]*bn[k])
        #             print(' ',k)
        #             print('  ',i)
        #             print('   ',j)
        #             print(rn)
        return rn+bias
a1 = [[[1,2,0,0],[0,1,-2,0],[0,0,1,2],[2,0,0,1]],[[1,0,0,0],[0,0,-2,-1],[3,0,1,0],[2,0,0,1]]]
a2 = [[[-1,0,3],[2,0,-1],[0,2,1]],[[0,0,0],[2,0,-1],[0,-2,1]]]
s1 = 1
b1 = 0
print(xx(a1,a2,s1,b1))

[[0 0]
 [0 0]]
[[5 3]
 [0 0]]


In [153]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
    #s = 2
    #bias = 1
        
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
    # print(an)
    # print(bn)
    print(rn)
    if len(an.shape) == 2:
        for i in range(an.shape[0]-bn.shape[0]+1):
            for j in range(an.shape[1]-bn.shape[1]+1):
                rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
        return rn+bias
    
    else:
        for i in range(math.ceil((an.shape[len(an)-2]-bn.shape[len(bn)-2]+1)/s)):
            for j in range(math.ceil((an.shape[len(an)-1]-bn.shape[len(bn)-1]+1)/s)):
                for k in range(len(bn)):
        #             print('---',an[k][i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]])
        #             print(bn[k])
        #             print(an[i*s:i*s+bn.shape[0],j*s:j*s+bn.shape[len(bn)-1]]*bn[k])
                    rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn.shape)-2],j*s:j*s+bn.shape[len(bn.shape)-1]]*bn[k])
                    print(' ',k)
                    print('  ',i)
                    print('   ',j)
                    print(rn)
        return rn+bias

a1 = [[[1,2,0,0],[0,1,-2,0],[0,0,1,2],[2,0,0,1]],[[1,0,0,0],[0,0,-2,-1],[3,0,1,0],[2,0,0,1]]]
a2 = [[[-1,0,3],[2,0,-1],[0,2,1]],[[0,0,0],[2,0,-1],[0,-2,1]]]
s1 = 1
b1 = 0
print(xx(a1,a2,s1,b1))

[[0 0]
 [0 0]]
  0
   0
    0
[[2 0]
 [0 0]]
  1
   0
    0
[[5 0]
 [0 0]]
  0
   0
    1
[[5 4]
 [0 0]]
  1
   0
    1
[[5 3]
 [0 0]]
[[5 3]
 [0 0]]


In [162]:

def xx(m_a,filt,s=1,bias=0):
    import numpy as np
    import math
        
    an = np.array(m_a)
    bn = np.array(filt)
    rn = np.array([[0]*math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)]*math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s))
    print(rn)
    if len(an.shape) == 2:
        for i in range(an.shape[0]-bn.shape[0]+1):
            for j in range(an.shape[1]-bn.shape[1]+1):
                rn[i][j] = np.sum(an[i:i+bn.shape[0],j:j+bn.shape[1]]*bn)
        
        return rn+bias
    
    else:
        for i in range(math.ceil((an.shape[len(an.shape)-2]-bn.shape[len(bn.shape)-2]+1)/s)):
            for j in range(math.ceil((an.shape[len(an.shape)-1]-bn.shape[len(bn.shape)-1]+1)/s)):
                for k in range(len(bn)):
                    rn[i][j] += np.sum(an[k][i*s:i*s+bn.shape[len(bn.shape)-2],j*s:j*s+bn.shape[len(bn.shape)-1]]*bn[k])
        return rn+bias

a1 = [[[1,2,0,0],[0,1,-2,0],[0,0,1,2],[2,0,0,1]],[[1,0,0,0],[0,0,-2,-1],[3,0,1,0],[2,0,0,1]]]
a2 = [[[-1,0,3],[2,0,-1],[0,2,1]],[[0,0,0],[2,0,-1],[0,-2,1]]]
s1 = 1
b1 = 0
print(xx(a1,a2,s1,b1))

[[0 0]
 [0 0]]
[[ 5  3]
 [-2 -1]]
